name: Tests

on:
  push:
    branches:
      - master
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Pull latest ShellCheck
        run: docker pull --quiet koalaman/shellcheck:stable
      - name: Show ShellCheck version
        run: docker run --rm koalaman/shellcheck:stable --version
      - name: Run ShellCheck
        run: docker run --rm --volume "$PWD:/mnt:ro" --workdir /mnt koalaman/shellcheck:stable bin/incremental-git-filterbranch test/bootstrap test/run-tests test/tests/*
  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Pull latest shfmt
        run: docker pull --quiet mvdan/shfmt:v3
      - name: Show shfmt version
        run: docker run --rm mvdan/shfmt:v3 --version
      - name: Run shfmt
        run: docker run --rm --volume "$PWD:/mnt:ro" --workdir /mnt mvdan/shfmt:v3 --diff bin/incremental-git-filterbranch test/bootstrap test/run-tests test/tests/*
  tests:
    name: Tests (${{ matrix.os }}, git ${{ matrix.git-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        git-version:
          - preinstalled
          - 2.16.6
          - 2.49.1
        include:
          - os: macos-latest
            git-version: preinstalled
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Configure git build
        if: matrix.git-version != 'preinstalled'
        id: git-build
        run: |
          echo "dir=$HOME/git-${{ matrix.git-version }}" >>"$GITHUB_OUTPUT"
          echo "cache-key=git-${{ matrix.git-version }}-$ImageOS-$RUNNER_ARCH-v2" >>"$GITHUB_OUTPUT"
      - name: Restore git from cache
        if: steps.git-build.outputs.dir
        id: git-cache
        uses: actions/cache@v6
        with:
          path: ${{ steps.git-build.outputs.dir }}
          key: ${{ steps.git-build.outputs.cache-key }}
      - name: Build git
        if: steps.git-build.outputs.dir && steps.git-cache.outputs.cache-hit != 'true'
        working-directory: ${{ runner.temp }}
        env:
          # We only work with local repositories, so we can skip most of the optional features
          NO_CURL: 1
          NO_EXPAT: 1
          NO_GETTEXT: 1
          NO_OPENSSL: 1
          NO_PYTHON: 1
          NO_RUST: 1
          NO_TCLTK: 1
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --yes --quiet --no-install-recommends gcc libc6-dev make perl xz-utils zlib1g-dev
          curl --silent --show-error --fail --location --output git.tar.xz "https://www.kernel.org/pub/software/scm/git/git-${{ matrix.git-version }}.tar.xz"
          tar --extract --file=git.tar.xz
          cd "git-${{ matrix.git-version }}"
          # Old git versions can't be compiled with the C standard used by default by recent compilers
          make "-j$(nproc)" "prefix=${{ steps.git-build.outputs.dir }}" 'CFLAGS=-g -O2 -std=gnu17' install
      - name: Use built git
        if: steps.git-build.outputs.dir
        run: echo "${{ steps.git-build.outputs.dir }}/bin" >>"$GITHUB_PATH"
      - name: Show git version
        run: git --version
      - name: Run tests
        run: ./test/run-tests
